-- MySQL Script generated by MySQL Workbench
-- Thu May  4 12:08:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S02T01N01Exercici2RUEDAIZQUIERDOMARINA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` ;

-- -----------------------------------------------------
-- Schema S02T01N01Exercici2RUEDAIZQUIERDOMARINA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` DEFAULT CHARACTER SET utf8 ;
USE `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` ;

-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Bebida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Bebida` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Bebida` (
  `BebidaID` INT NOT NULL AUTO_INCREMENT,
  `ProductoID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`BebidaID`))
ENGINE = InnoDB;

CREATE INDEX `ProductoID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Bebida` (`ProductoID` ASC) VISIBLE;

CREATE UNIQUE INDEX `ProductoID_UNIQUE` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Bebida` (`ProductoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Cliente` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ClienteID_UNIQUE` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Cliente` (`ClienteID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Empleado` (
  `EmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nif` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `TipoEmpleado` VARCHAR(45) NOT NULL,
  `TiendaID` INT NOT NULL,
  PRIMARY KEY (`EmpleadoID`))
ENGINE = InnoDB;

CREATE INDEX `TiendaID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Empleado` (`TiendaID` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nif_UNIQUE` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Empleado` (`Nif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Hamburguesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Hamburguesa` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Hamburguesa` (
  `HamburguesaID` INT NOT NULL AUTO_INCREMENT,
  `ProductoID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`HamburguesaID`))
ENGINE = InnoDB;

CREATE INDEX `ProductoID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Hamburguesa` (`ProductoID` ASC) VISIBLE;

CREATE UNIQUE INDEX `ProductoID_UNIQUE` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Hamburguesa` (`ProductoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`PedidoDomicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`PedidoDomicilio` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`PedidoDomicilio` (
  `PedidoID` INT NOT NULL,
  `EmpleadoID` INT NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  PRIMARY KEY (`PedidoID`, `EmpleadoID`))
ENGINE = InnoDB;

CREATE INDEX `EmpleadoID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`PedidoDomicilio` (`EmpleadoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos` (
  `PedidosID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NULL,
  `TiendaID` INT NULL,
  `EmpleadoID` INT NULL,
  `FechaHora` DATETIME NOT NULL,
  `Entrega` VARCHAR(45) NOT NULL,
  `PrecioTotal` FLOAT ZEROFILL NOT NULL,
  PRIMARY KEY (`PedidosID`))
ENGINE = InnoDB;

CREATE INDEX `TiendaID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos` (`TiendaID` ASC) VISIBLE;

CREATE INDEX `ClienteID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos` (`ClienteID` ASC) VISIBLE;

CREATE INDEX `EmpleadoID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pedidos` (`EmpleadoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pizza` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pizza` (
  `PizzaID` INT NOT NULL AUTO_INCREMENT,
  `ProductoID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`PizzaID`))
ENGINE = InnoDB;

CREATE INDEX `ProductoID_idx` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pizza` (`ProductoID` ASC) VISIBLE;

CREATE UNIQUE INDEX `ProductoID_UNIQUE` ON `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Pizza` (`ProductoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Producto` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Producto` (
  `ProductoID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ProductoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Tienda` ;

CREATE TABLE IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA`.`Tienda` (
  `TiendaID` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NOT NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TiendaID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
