-- MySQL Script generated by MySQL Workbench
-- Mon May  8 12:58:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S02T01N01Exercici2RUEDAIZQUIERDOMARINA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` ;

-- -----------------------------------------------------
-- Schema S02T01N01Exercici2RUEDAIZQUIERDOMARINA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` DEFAULT CHARACTER SET utf8 ;
USE `S02T01N01Exercici2RUEDAIZQUIERDOMARINA` ;

-- -----------------------------------------------------
-- Table `FamiliaProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FamiliaProducto` ;

CREATE TABLE IF NOT EXISTS `FamiliaProducto` (
  `ProductoID` INT NOT NULL AUTO_INCREMENT,
  `TipoPizza` VARCHAR(45) NULL,
  PRIMARY KEY (`ProductoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Producto` ;

CREATE TABLE IF NOT EXISTS `Producto` (
  `ProductoID` INT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`ProductoID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ProductoID_UNIQUE` ON `Producto` (`ProductoID` ASC) VISIBLE;

CREATE UNIQUE INDEX `ProductoID_UNIQUE` ON `Producto` (`ProductoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

CREATE TABLE IF NOT EXISTS `Cliente` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ClienteID_UNIQUE` ON `Cliente` (`ClienteID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tienda` ;

CREATE TABLE IF NOT EXISTS `Tienda` (
  `TiendaID` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NOT NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TiendaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleado` ;

CREATE TABLE IF NOT EXISTS `Empleado` (
  `EmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nif` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `TipoEmpleado` VARCHAR(45) NOT NULL,
  `TiendaID` INT NOT NULL,
  PRIMARY KEY (`EmpleadoID`))
ENGINE = InnoDB;

CREATE INDEX `TiendaID_idx` ON `Empleado` (`TiendaID` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nif_UNIQUE` ON `Empleado` (`Nif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedidos` ;

CREATE TABLE IF NOT EXISTS `Pedidos` (
  `PedidosID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NULL,
  `TiendaID` INT NULL,
  `EmpleadoID` INT NULL,
  `FechaHora` DATETIME NOT NULL,
  `Entrega` VARCHAR(45) NOT NULL,
  `PrecioTotal` FLOAT ZEROFILL NOT NULL,
  PRIMARY KEY (`PedidosID`))
ENGINE = InnoDB;

CREATE INDEX `TiendaID_idx` ON `Pedidos` (`TiendaID` ASC) VISIBLE;

CREATE INDEX `ClienteID_idx` ON `Pedidos` (`ClienteID` ASC) VISIBLE;

CREATE INDEX `EmpleadoID_idx` ON `Pedidos` (`EmpleadoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PedidoDomicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PedidoDomicilio` ;

CREATE TABLE IF NOT EXISTS `PedidoDomicilio` (
  `PedidoID` INT NOT NULL,
  `EmpleadoID` INT NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  PRIMARY KEY (`PedidoID`, `EmpleadoID`))
ENGINE = InnoDB;

CREATE INDEX `EmpleadoID_idx` ON `PedidoDomicilio` (`EmpleadoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DetallePedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DetallePedido` ;

CREATE TABLE IF NOT EXISTS `DetallePedido` (
  `DetallePedidoID` INT NOT NULL AUTO_INCREMENT,
  `PedidoID` INT NOT NULL,
  `ProductoID` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`DetallePedidoID`))
ENGINE = InnoDB;

CREATE INDEX `ProductoID_idx` ON `DetallePedido` (`ProductoID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
